# Generated by Django 4.2 on 2023-05-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project_img',
            field=models.FileField(upload_to='media/Project/images/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.FileField(upload_to='media/Product/images/')),
                ('product_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
